In [1]:
import numpy as np

In [2]:
list = [1,2,3]

In [3]:
type(list)

list

In [10]:
arr = np.array(list)
#np. to call numpy and method needed

In [11]:
type(arr)

numpy.ndarray

In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
#To make 2d matrix, initalize as a list

In [13]:
array = np.array(my_matrix)

In [14]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,11)
#To generate array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(0,11,2)
#To generate array, third argument is step size

array([ 0,  2,  4,  6,  8, 10])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,2))
#Pass in a tuple for a 2d matrix

array([[0., 0.],
       [0., 0.]])

In [27]:
np.ones((3,3))
#np.ones to generate ones matrix
#np.zeros to generate zeros matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.linspace(0,5,10)
#Ten evenly spaced points from 0 to 5
#One dimensional array since evident it has 1 set of brackets

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.eye(5)
#np.eye to make an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/random/__init__.py'>
File:        /opt/anaconda3/lib/python3.8/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerator

In [38]:
np.random.rand(5)

array([0.3512732 , 0.20013649, 0.60225463, 0.42180817, 0.27660953])

In [41]:
np.random.rand(3,3)
#random.rand will generate random numbers from 0 to 1

array([[0.83306417, 0.41133626, 0.20962724],
       [0.98183152, 0.33533941, 0.14125941],
       [0.92065381, 0.69828626, 0.31746309]])

In [43]:
np.random.randn(2)
#random.randn to generate values from random distribution

array([ 0.41961253, -0.48246758])

In [44]:
np.random.randn(3,3)

array([[-0.04750879,  1.16984124,  1.09767438],
       [ 0.07238291, -0.07542126,  0.1622574 ],
       [ 0.26469862,  0.61184867, -0.62830204]])

In [47]:
np.random.randint(1,100,5)

array([94, 72, 79, 22, 80])

In [48]:
arr = np.arange(25)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr =  np.random.randint(1,10,5)

In [51]:
ranarr

array([7, 6, 7, 2, 1])

In [52]:
ranarr =  np.random.randint(1,100,10)

In [53]:
ranarr

array([41,  5, 78, 41, 60, 93, 68, 69, 87, 12])

In [55]:
ranarr.reshape(5,2)

array([[41,  5],
       [78, 41],
       [60, 93],
       [68, 69],
       [87, 12]])

In [56]:
ranarr.reshape(2,5)

array([[41,  5, 78, 41, 60],
       [93, 68, 69, 87, 12]])

In [58]:
ranarr.max()

93

In [59]:
ranarr.min()

5

In [60]:
ranarr

array([41,  5, 78, 41, 60, 93, 68, 69, 87, 12])

In [61]:
ranarr.argmax()

5

In [62]:
ranarr.argmin()

1

In [64]:
ranarr.shape

(10,)

In [65]:
ranarrreshape = ranarr.reshape(2,5)

In [66]:
ranarrreshape.shape

(2, 5)

In [70]:
arr.dtype

dtype('int64')

In [74]:
#useful import technique
from numpy.random import randint as ri

ri(5,10)

7

In [75]:
ri(10,100)

35